# Identification projet SonarQube
sonar.projectKey=mmd-full-stack
sonar.projectName=mmd-full-stack
sonar.sourceEncoding=UTF-8
sonar.projectVersion=0.1.0

# Ce que Sonar analyse
sonar.sources=front/src,back/src/main/java
sonar.tests=front/src,back/src/test/java

# Marquer les tests (utile côté front où tests et sources sont mélangés)
sonar.test.inclusions=front/src/**/*.spec.ts,back/src/test/**/*

# Exclusions classiques mono-repo
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/target/**,**/.angular/**,**/.sonar/**

# Coverage Front (LCOV)
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info

# Coverage Back (JaCoCo XML)
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# Java bytecode (sinon tu peux avoir des règles Java “dégradées”)
sonar.java.binaries=back/target/classes
sonar.java.test.binaries=back/target/test-classes

# TypeScript : évite que le scanner traverse tout le repo à la recherche de tsconfig (peut ralentir en mono-repo)
sonar.typescript.tsconfigPaths=front/tsconfig.sonar.app.json,front/tsconfig.sonar.spec.json

# Exclusions de couverture (on garde l'analyse, on enlève juste du coverage)
sonar.coverage.exclusions=front/src/main.ts,front/src/app/app.config.ts,front/src/app/app.routes.ts,back/src/main/java/**/bootstrap/**,back/src/main/java/**/*Seeder.java

